- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v2.5.0"
  hooks:
    - id: check-merge-conflict
    - id: debug-statements

- repo: local

  hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [
            "--ignore=E203,E800,W503,TAE001,ANN001,ANN101,ANN201",
            "--exclude=volts/settings/*,volts,manage.py",
            "--max-line-length=79",
        ]

    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: system
      types: [python]
      args: [--py37-plus]
